#!/bin/bash

export PATH=$PATH:/usr/sbin:/usr/bin:/sbin:/bin

if [[ ! -e /var/lib/cydia/firmware.ver ]]; then
    cache=
fi

/usr/libexec/zebra/firmware

if [[ ${cache+@} ]]; then
    sbdidlaunch
    su -c uicache mobile
fi
