commit_message: "[Localization] Update %osx_code%"                
append_commit_message: false
files:
  - source: /Zebra/Base.lproj/Localizable.strings
    translation: /Zebra/%osx_code%/Localizable.strings
