//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCache;

@interface PSAppDataUsagePolicyCache : NSObject
{
    NSCache *_policyCache;
    struct __CTServerConnection *_ctServerConnection;
}

+ (id)sharedInstance;
@property(retain, nonatomic) struct __CTServerConnection *ctServerConnection; // @synthesize ctServerConnection=_ctServerConnection;
@property(retain, nonatomic) NSCache *policyCache; // @synthesize policyCache=_policyCache;
- (_Bool)setUsagePoliciesForBundle:(id)arg1 cellular:(_Bool)arg2 wifi:(_Bool)arg3;
- (_Bool)setCellularUsagePolicy:(id)arg1 forBundle:(id)arg2;
- (id)usagePolicyFor:(id)arg1;
- (id)fetchUsagePolicyFor:(id)arg1;
- (id)init;
- (void)willEnterForeground;
- (void)dealloc;
- (id)initPrivate;

@end