#!/bin/sh

# Verify supersling permissions
chown root:wheel /usr/libexec/zebra/supersling
chmod 6755 /usr/libexec/zebra/supersling

# Setup relaunch Launch Daemon
launchctl load /Library/LaunchDaemons/xyz.willy.Zebra.Relaunch.plist

# Prevent Zebra from choosing a sandbox path for its directory
if [ -f /var/mobile/Containers/Data/Application/*/Documents/zebra.db ];then
    DBPATH=$(ls /var/mobile/Containers/Data/Application/*/Documents/zebra.db)
    ZBPATH=${DBPATH/Documents\/zebra.db/}
    rm -rf ${ZBPATH}
    echo "Removed sandboxed Zebra document directory"
fi

if [ -d "/var/mobile/Library/Application Support/xyz.willy.Zebra" ];then
    chown -R mobile:mobile "/var/mobile/Library/Application Support/xyz.willy.Zebra"
    chmod -R +r "/var/mobile/Library/Application Support/xyz.willy.Zebra"
fi

mkdir /var/mobile/Library/Caches/xyz.willy.Zebra
chown mobile:mobile /var/mobile/Library/Caches/xyz.willy.Zebra

mkdir /var/mobile/Library/Caches/xyz.willy.Zebra/lists
mkdir /var/mobile/Library/Caches/xyz.willy.Zebra/lists/partial
chown mobile:mobile /var/mobile/Library/Caches/xyz.willy.Zebra/lists
chown mobile:mobile /var/mobile/Library/Caches/xyz.willy.Zebra/lists/partial

mkdir /var/mobile/Library/Caches/xyz.willy.Zebra/logs
chown mobile:mobile /var/mobile/Library/Caches/xyz.willy.Zebra/logs