#!/bin/sh

finish() {
	f="${1}"

	[ -z "${f}" ] || [ -z "${CYDIA}" ] && return

	read -r fd ver <<-EOF
			${CYDIA}
			EOF

	[ "${ver}" -ge 1 ] || return

	echo "finish:${f}" >&"${fd}"
}

finish uicache

exit 0
