include $(THEOS)/makefiles/common.mk

TOOL_NAME = supersling

supersling_FILES = main.c
supersling_CODESIGN_FLAGS = -Sent.plist
supersling_INSTALL_PATH = /usr/libexec/zebra

include $(THEOS_MAKE_PATH)/tool.mk
